prog:main.o Personne.o enemy.o
	gcc main.o Personne.o enemy.o -o prog -lSDL -lSDL_image

main.o: main.c
	gcc -c main.c -g
personne.o: Personne.c 
	gcc -c personne.c -g 
enemy.o: enemy.c 
	gcc -c enemy.c -g 



